import { area, date, select, text, toneOptions, upload, type TaskTemplateSpec } from "./shared.js";

export const documentsTemplateSpecs: TaskTemplateSpec[] = [
  {
    id: "meeting-minutes-action-items",
    name: "Meeting Minutes & Action Items",
    description: "สรุปการประชุม แยกมติ ผู้รับผิดชอบ กำหนดเวลา และประเด็นติดตาม",
    category: "documents", icon: "MIN", tags: ["ประชุม", "สรุป", "Action Items"], featured: true, estimatedMinutes: 4, requiresFile: false,
    starterPrompt: "สร้างเว็บบันทึกการประชุม มีแบบฟอร์ม ผลสรุป มติ และ Action Items",
    role: "เลขานุการประชุมและ Project Coordinator",
    instructions: "จัดทำ Minutes of Meeting โดยแยกวาระ สาระสำคัญ มติ งานที่ต้องทำ ผู้รับผิดชอบ วันครบกำหนด ความเสี่ยง และคำถามที่ยังไม่ได้ข้อสรุป ห้ามเดาชื่อหรือกำหนดเวลา",
    inputs: [text("meetingTitle", "ชื่อการประชุม", true), date("meetingDate", "วันที่ประชุม", true), area("participants", "ผู้เข้าร่วมและบทบาท", true), area("meetingNotes", "บันทึกหรือ Transcript", true), select("tone", "รูปแบบภาษา", toneOptions)],
  },
  {
    id: "executive-brief",
    name: "Executive Brief from Document",
    description: "ย่อเอกสารยาวให้เหลือประเด็นตัดสินใจ ความเสี่ยง และสิ่งที่ผู้บริหารต้องรู้",
    category: "documents", icon: "BRF", tags: ["ผู้บริหาร", "เอกสาร", "Decision"], featured: true, estimatedMinutes: 5, requiresFile: true,
    starterPrompt: "สร้างเว็บ Executive Brief สำหรับอัปโหลดเอกสารและสรุปประเด็นตัดสินใจ",
    role: "ที่ปรึกษากลยุทธ์และนักวิเคราะห์สำหรับผู้บริหาร",
    instructions: "จัดทำ Executive Brief โดยแยกสถานการณ์ ข้อเท็จจริง ตัวเลขที่พบ ทางเลือก ผลกระทบ ความเสี่ยง ประเด็นที่ต้องตัดสินใจ และข้อมูลที่ยังขาด ใช้เฉพาะข้อมูลในไฟล์",
    fileField: "sourceFile",
    inputs: [text("briefTitle", "ชื่อเรื่อง", true), text("audience", "ผู้รับรายงาน", true, "เช่น CEO, CIO, คณะกรรมการ"), area("decisionQuestion", "คำถามที่ต้องการคำตอบ", true), upload("sourceFile", "เอกสารต้นทาง", [".pdf", ".docx", ".txt", ".csv", ".xlsx"], true)],
  },
  {
    id: "business-proposal-draft",
    name: "Business Proposal Draft",
    description: "สร้างร่างข้อเสนอโครงการที่มีปัญหา แนวทาง ประโยชน์ แผนงาน งบประมาณ และ KPI",
    category: "documents", icon: "PRO", tags: ["Proposal", "โครงการ", "Business Case"], featured: true, estimatedMinutes: 7, requiresFile: false,
    starterPrompt: "สร้างเว็บช่วยเขียน Business Proposal มี Pain Point, Solution, Budget, Timeline และ KPI",
    role: "ที่ปรึกษาธุรกิจและนักเขียนข้อเสนอโครงการ",
    instructions: "จัดทำข้อเสนอที่มีบทสรุป ปัญหาและหลักฐาน กลุ่มเป้าหมาย แนวทาง ขอบเขต ผลลัพธ์ KPI แผนงาน งบประมาณตามตัวเลขที่ให้ ความเสี่ยง และคำขออนุมัติ",
    inputs: [text("proposalTitle", "ชื่อข้อเสนอ", true), area("problem", "ปัญหาและผลกระทบ", true), area("solution", "แนวทางที่เสนอ", true), text("targetAudience", "ลูกค้าหรือผู้อนุมัติ", true), text("budget", "กรอบงบประมาณ"), text("timeline", "ระยะเวลาดำเนินการ"), area("successMetrics", "KPI หรือผลสำเร็จ")],
  },
  {
    id: "sop-writer",
    name: "SOP & Work Instruction Writer",
    description: "แปลงขั้นตอนงานกระจัดกระจายให้เป็น SOP ที่มีบทบาท จุดควบคุม และหลักฐาน",
    category: "documents", icon: "SOP", tags: ["SOP", "Process", "Quality"], featured: false, estimatedMinutes: 6, requiresFile: false,
    starterPrompt: "สร้างเว็บเขียน SOP พร้อมวัตถุประสงค์ ขอบเขต RACI ขั้นตอน และจุดควบคุม",
    role: "ผู้เชี่ยวชาญระบบคุณภาพและ Process Improvement",
    instructions: "จัดทำ SOP โดยมีวัตถุประสงค์ ขอบเขต คำจำกัดความ บทบาท เงื่อนไขก่อนเริ่ม ขั้นตอน จุดควบคุม หลักฐาน Exception การ Escalate และ KPI ห้ามเพิ่มข้อกำหนดที่ไม่ได้รับ",
    inputs: [text("processName", "ชื่อกระบวนการ", true), area("objective", "วัตถุประสงค์", true), area("scope", "ขอบเขต", true), area("roles", "ผู้เกี่ยวข้องและหน้าที่", true), area("currentSteps", "ขั้นตอนปัจจุบัน", true), area("controls", "จุดตรวจหรือข้อควบคุม")],
  },
  {
    id: "contract-review-checklist",
    name: "Contract Review Checklist",
    description: "สรุปเงื่อนไขสำคัญ จุดเสี่ยง ภาระผูกพัน และคำถามสำหรับฝ่ายกฎหมาย",
    category: "documents", icon: "CTR", tags: ["สัญญา", "Checklist", "Risk"], featured: true, estimatedMinutes: 8, requiresFile: true,
    starterPrompt: "สร้างเว็บตรวจสัญญาเบื้องต้น สรุปหน้าที่ เงื่อนไข จุดเสี่ยง และ Checklist",
    role: "ผู้ช่วยตรวจเอกสารสัญญาเชิงธุรกิจ ไม่ใช่ทนายความ",
    instructions: "สรุปคู่สัญญา ระยะเวลา ราคา SLA หน้าที่ การรับประกัน PDPA ทรัพย์สินทางปัญญา ความรับผิด การยกเลิก การต่ออายุ และเงื่อนไขผิดปกติ พร้อมคำถามให้ฝ่ายกฎหมาย ห้ามให้ข้อสรุปทางกฎหมายเด็ดขาด",
    fileField: "contractFile",
    inputs: [text("contractName", "ชื่อสัญญา", true), area("reviewFocus", "ประเด็นที่ต้องเน้น"), area("businessContext", "บริบทธุรกิจ"), upload("contractFile", "ไฟล์สัญญา", [".pdf", ".docx", ".txt"], true)],
  },
  {
    id: "policy-gap-analysis",
    name: "Policy Gap Analysis",
    description: "เปรียบเทียบนโยบายปัจจุบันกับเป้าหมายและสร้างรายการช่องว่างที่ต้องแก้",
    category: "documents", icon: "GAP", tags: ["Policy", "Compliance", "Gap"], featured: false, estimatedMinutes: 8, requiresFile: true,
    starterPrompt: "สร้างเว็บ Policy Gap Analysis ที่อัปโหลดนโยบายและออก Action Plan",
    role: "นักวิเคราะห์นโยบายและ Compliance",
    instructions: "แยกหัวข้อที่มีแล้ว บางส่วน ยังไม่มี หลักฐานที่ต้องขอ ความเสี่ยง เจ้าของงาน และลำดับความสำคัญ ไม่อ้างว่าผ่านมาตรฐานหากไม่มีหลักฐาน",
    fileField: "policyFile",
    inputs: [text("policyName", "ชื่อนโยบาย", true), text("targetStandard", "มาตรฐานหรือเป้าหมาย", true), area("focusAreas", "หัวข้อที่ต้องตรวจ"), upload("policyFile", "ไฟล์นโยบายปัจจุบัน", [".pdf", ".docx", ".txt"], true)],
  },
];
