import { ModuleRegistry, type WorkflowData } from "@cherryflow/workflow-engine";
import type { FileOutputValue, UploadedFileValue } from "@cherryflow/ui-schema";
import { createCherryAgentModuleDefinition } from "./cherry-agent.js";
import { createFileOutput } from "./file-storage.js";
import { createOpenClawModuleDefinition } from "./openclaw-module.js";

function isUploadedFile(value: unknown): value is UploadedFileValue {
  return Boolean(value && typeof value === "object" && "name" in value && ("dataUrl" in value || "objectKey" in value) && "size" in value);
}

function textDownload(name: string, text: string): Promise<FileOutputValue> {
  return createFileOutput(name, "text/plain;charset=utf-8", text);
}

function dependency(dependencies: Record<string, WorkflowData>, nodeId: string): WorkflowData {
  const value = dependencies[nodeId];
  if (!value) throw new Error(`Missing dependency output: ${nodeId}`);
  return value;
}

export const moduleRegistry = new ModuleRegistry()
  .register({
    type: "core.input",
    label: "Workflow Input",
    description: "Expose validated workflow form values to downstream nodes.",
    run: ({ workflowInputs }) => workflowInputs,
  })
  .register({
    type: "file.inspect",
    label: "Inspect Uploaded File",
    description: "Validate an uploaded file and expose safe metadata.",
    run: ({ dependencies, config }) => {
      const source = dependency(dependencies, String(config.inputNode ?? "input"));
      const field = String(config.field ?? "sourceFile");
      const file = source[field];
      if (!isUploadedFile(file)) throw new Error(`${field} is required`);
      const maxBytes = Number(config.maxBytes ?? 5 * 1024 * 1024);
      if (file.size > maxBytes) throw new Error(`File exceeds the ${Math.round(maxBytes / 1024 / 1024)} MB limit`);
      return { name: file.name, type: file.type, size: file.size };
    },
  })
  .register({
    type: "report.compose",
    label: "Compose Report",
    description: "Create report outputs from workflow inputs and inspected file metadata.",
    run: async ({ dependencies, config }) => {
      const input = dependency(dependencies, String(config.inputNode ?? "input"));
      const file = dependency(dependencies, String(config.fileNode ?? "inspect"));
      const projectName = String(input.projectName ?? "Untitled project");
      const department = String(input.department ?? "unspecified");
      const notes = String(input.notes ?? "").trim();
      const fileName = String(file.name ?? "source-file");
      const fileSize = Number(file.size ?? 0);

      await new Promise((resolve) => setTimeout(resolve, 300));

      const summary = [
        `# ${projectName}`,
        "",
        `CherryFlow processed ${fileName} for the ${department} department.`,
        `The source file size is ${(fileSize / 1024).toFixed(1)} KB.`,
        notes ? `Additional instruction: ${notes}` : "No additional instruction was provided.",
        "",
        "This workflow was executed through the CherryFlow graph engine.",
      ].join("\n");

      const reportText = [
        projectName,
        `Department: ${department}`,
        `Source: ${fileName}`,
        `Size: ${fileSize} bytes`,
        `Notes: ${notes || "-"}`,
        "",
        "Generated by CherryFlow.",
      ].join("\n");

      return {
        summary,
        metrics: [
          { metric: "Project", value: projectName },
          { metric: "Department", value: department },
          { metric: "Source file", value: fileName },
          { metric: "File size (KB)", value: Number((fileSize / 1024).toFixed(1)) },
        ],
        reportFile: await textDownload(`${projectName.replace(/\s+/g, "-").toLowerCase()}-report.txt`, reportText),
      };
    },
  })
  .register(createCherryAgentModuleDefinition())
  .register(createOpenClawModuleDefinition())
  .register({
    type: "core.output",
    label: "Workflow Output",
    description: "Expose one upstream node as the final workflow output.",
    run: ({ dependencies, config }) => dependency(dependencies, String(config.sourceNode ?? "compose")),
  });
