import type { FileOutputValue, UploadedFileValue, WorkflowInputValues, WorkflowOutputValues } from "@cherryflow/ui-schema";
import type { WorkflowDefinition } from "./types.js";

function isUploadedFile(value: unknown): value is UploadedFileValue {
  return Boolean(value && typeof value === "object" && "name" in value && "dataUrl" in value);
}

function textDownload(name: string, text: string): FileOutputValue {
  return {
    name,
    mimeType: "text/plain;charset=utf-8",
    dataUrl: `data:text/plain;charset=utf-8;base64,${Buffer.from(text, "utf8").toString("base64")}`,
  };
}

const reportGenerator: WorkflowDefinition = {
  contract: {
    id: "report-generator",
    name: "AI Report Generator",
    description: "Upload a source file and generate a structured report package.",
    inputs: [
      { name: "projectName", label: "ชื่อโครงการ", type: "text", placeholder: "เช่น รายงานยอดขายประจำเดือน", required: true },
      {
        name: "department",
        label: "หน่วยงาน",
        type: "select",
        required: true,
        options: [
          { label: "บริหาร", value: "management" },
          { label: "ปฏิบัติการ", value: "operations" },
          { label: "เทคโนโลยี", value: "technology" },
        ],
      },
      {
        name: "sourceFile",
        label: "ไฟล์ข้อมูล",
        type: "file",
        description: "รองรับ Excel, CSV, PDF และข้อความ ขนาดไม่เกิน 5 MB",
        accept: [".xlsx", ".csv", ".pdf", ".txt"],
        required: true,
      },
      { name: "notes", label: "คำอธิบายเพิ่มเติม", type: "textarea", placeholder: "จุดที่ต้องการให้ AI เน้นเป็นพิเศษ" },
    ],
    outputs: [
      { name: "summary", label: "สรุปผล", type: "markdown" },
      { name: "metrics", label: "ข้อมูลสำคัญ", type: "table" },
      { name: "reportFile", label: "ดาวน์โหลดรายงาน", type: "file" },
    ],
  },
  async execute(inputs: WorkflowInputValues): Promise<WorkflowOutputValues> {
    const projectName = String(inputs.projectName ?? "Untitled project");
    const department = String(inputs.department ?? "unspecified");
    const notes = String(inputs.notes ?? "").trim();
    const sourceFile = inputs.sourceFile;

    if (!isUploadedFile(sourceFile)) throw new Error("sourceFile is required");
    if (sourceFile.size > 5 * 1024 * 1024) throw new Error("File exceeds the 5 MB limit");

    await new Promise((resolve) => setTimeout(resolve, 900));

    const summary = [
      `# ${projectName}`,
      "",
      `CherryFlow processed ${sourceFile.name} for the ${department} department.`,
      `The source file size is ${(sourceFile.size / 1024).toFixed(1)} KB.`,
      notes ? `Additional instruction: ${notes}` : "No additional instruction was provided.",
      "",
      "This built-in workflow demonstrates the complete frontend, run, and output path.",
    ].join("\n");

    const reportText = [
      projectName,
      `Department: ${department}`,
      `Source: ${sourceFile.name}`,
      `Size: ${sourceFile.size} bytes`,
      `Notes: ${notes || "-"}`,
      "",
      "Generated by CherryFlow.",
    ].join("\n");

    return {
      summary,
      metrics: [
        { metric: "Project", value: projectName },
        { metric: "Department", value: department },
        { metric: "Source file", value: sourceFile.name },
        { metric: "File size (KB)", value: Number((sourceFile.size / 1024).toFixed(1)) },
      ],
      reportFile: textDownload(`${projectName.replace(/\s+/g, "-").toLowerCase()}-report.txt`, reportText),
    };
  },
};

const definitions = new Map<string, WorkflowDefinition>([[reportGenerator.contract.id, reportGenerator]]);

export function listWorkflows() {
  return [...definitions.values()].map((definition) => definition.contract);
}

export function getWorkflow(workflowId: string): WorkflowDefinition | undefined {
  return definitions.get(workflowId);
}
